services:
  - type: web
    name: portal-tickets
    runtime: python
    region: frankfurt
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app -b 0.0.0.0:$PORT
    healthCheckPath: /login
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: tickets-db
          property: connectionString
      - key: ADMIN_EMAIL
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: ADMIN_NAME
        value: Administrador
      # Email settings (rellenar en el panel o aquí)
      - key: MAIL_SERVER
        sync: false
      - key: MAIL_PORT
        sync: false
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_PASSWORD
        sync: false
      - key: MAIL_USE_TLS
        value: "true"
      - key: MAIL_USE_SSL
        value: "false"
      - key: MAIL_DEFAULT_SENDER
        sync: false

databases:
  - name: tickets-db
    plan: free
    region: frankfurt
    databaseName: tickets
    user: tickets_user
